
version: '3.7'

services:

  springboot:
    image: yisc/springboot
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - bridge

  mysql:
    image: yisc/mysql-8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BBdb
    networks:
      - bridge


networks:
  bridge:
